#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

set -e

cleanCase0

rm -rf *.png > /dev/null 2>&1


# ------------------------------------------------------------------------------
